namespace myPOS
{
	public enum TransactionStatus
	{
		Success = 0,
		Busy = 1,
		SyntaxError = 2,
		UnsupportedParam = 3,
		UnsupportedMethod = 4,
		NoCardFound = 5,
		UnsupportedCard = 6,
		CardChipError = 7,
		FallbackToMagstripe = 8,
		InvalidPin = 9,
		PinCountLimitExceeded = 10,
		PinCheckOnline = 11,
		InvalidDataFromHost = 12,
		UserCancel = 13,
		InternalError = 14,
		CommunicationError = 0xF,
		SSLError = 0x10,
		TransactionNotFound = 17,
		ReversalNotFound = 18,
		InvalidAmount = 19,
		LastTransactionIncomplete = 20,
		NoPrinterAvailable = 21,
		NoPaper = 22,
		IncorrectDataForPrint = 23,
		IncorrectLogoIndex = 24,
		ActivationRequired = 25,
		MandatoryUpdateRequired = 26,
		TerminalAlreadyActive = 27,
		ActivationUnsuccessful = 28,
		NoUpdateFound = 29,
		SoftwareUpdateUnsuccessful = 30,
		SoftwareUpdateWaitHost = 0x1F,
		SoftwareUpdateDontWaitHost = 0x20,
		DeactivationUnsuccessful = 33,
		OptionalUpdateRequired = 34,
		WrongCode = 35,
		DeactivationNotFinished = 36,
		FingerprintNotFound = 37,
		UnsupportedProtocolVersion = 38,
		WrongPreauthCode = 39,
		PreauthCompleted = 40,
		RemotelyActivated = 41,
		IvalidPAN = 47,
		InvalidExpiryDate = 48,
		WrongPassword = 49,
		SuccessWithInfo = 100,
		Timeout = -1
	}
}
